package com.peace.application.views.register;

import com.peace.application.views.MainLayout;
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.datepicker.DatePicker;
import com.vaadin.flow.component.dependency.Uses;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.icon.Icon;
import com.vaadin.flow.component.login.LoginForm;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexComponent.Alignment;
import com.vaadin.flow.component.orderedlayout.FlexComponent.JustifyContentMode;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.EmailField;
import com.vaadin.flow.component.textfield.TextArea;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.router.RouteAlias;
import com.vaadin.flow.router.RouterLink;
import com.vaadin.flow.theme.lumo.LumoUtility.Gap;
import java.util.ArrayList;
import java.util.List;

@PageTitle("Register")
@Route(value = "register", layout = MainLayout.class)
@RouteAlias(value = "", layout = MainLayout.class)
@Uses(Icon.class)
public class RegisterView extends Composite<VerticalLayout> {

    public RegisterView() {
        VerticalLayout layoutColumn2 = new VerticalLayout();
        H3 h3 = new H3();
        FormLayout formLayout2Col = new FormLayout();
        TextField textField = new TextField();
        TextField textField2 = new TextField();
        DatePicker datePicker = new DatePicker();
        TextField textField3 = new TextField();
        EmailField emailField = new EmailField();
        TextField textField4 = new TextField();
        TextField textField5 = new TextField();
        ComboBox comboBox = new ComboBox();
        TextArea textArea = new TextArea();
        VerticalLayout layoutColumn3 = new VerticalLayout();
        Paragraph textMedium = new Paragraph();
        HorizontalLayout layoutRow = new HorizontalLayout();
        TextField textField6 = new TextField();
        TextField textField7 = new TextField();
        HorizontalLayout layoutRow2 = new HorizontalLayout();
        TextField textField8 = new TextField();
        TextField textField9 = new TextField();
        HorizontalLayout layoutRow3 = new HorizontalLayout();
        TextField textField10 = new TextField();
        TextField textField11 = new TextField();
        HorizontalLayout layoutRow4 = new HorizontalLayout();
        TextField textField12 = new TextField();
        TextField textField13 = new TextField();
        TextField textField14 = new TextField();
        LoginForm loginForm = new LoginForm();
        RouterLink routerLink = new RouterLink();
        HorizontalLayout layoutRow5 = new HorizontalLayout();
        Button buttonPrimary = new Button();
        Button buttonSecondary = new Button();
        getContent().setWidth("100%");
        getContent().getStyle().set("flex-grow", "1");
        getContent().setJustifyContentMode(JustifyContentMode.START);
        getContent().setAlignItems(Alignment.CENTER);
        layoutColumn2.setWidth("100%");
        layoutColumn2.setMaxWidth("800px");
        layoutColumn2.setHeight("min-content");
        h3.setText("Doctor Registration");
        layoutColumn2.setAlignSelf(FlexComponent.Alignment.CENTER, h3);
        h3.setWidth("max-content");
        formLayout2Col.setWidth("100%");
        textField.setLabel("Name");
        textField2.setLabel("License Number");
        datePicker.setLabel("Date of Birth");
        textField3.setLabel("Phone Number");
        emailField.setLabel("Email");
        textField4.setLabel("Address");
        textField5.setLabel("Issuing Authority");
        textField5.setWidth("min-content");
        comboBox.setLabel("Gender");
        comboBox.setWidth("min-content");
        setComboBoxSampleData(comboBox);
        textArea.setLabel("Provide a link to your medical certificate here.");
        textArea.setWidth("100%");
        layoutColumn3.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutColumn3);
        layoutColumn3.setWidth("100%");
        layoutColumn3.getStyle().set("flex-grow", "1");
        textMedium.setText("Professional References (optional)");
        layoutColumn3.setAlignSelf(FlexComponent.Alignment.CENTER, textMedium);
        textMedium.setWidth("250px");
        textMedium.getStyle().set("font-size", "var(--lumo-font-size-m)");
        layoutRow.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow);
        layoutRow.addClassName(Gap.MEDIUM);
        layoutRow.setWidth("100%");
        layoutRow.getStyle().set("flex-grow", "1");
        textField6.setLabel("Name");
        textField6.getStyle().set("flex-grow", "1");
        textField7.setLabel("Affiliation");
        textField7.getStyle().set("flex-grow", "1");
        layoutRow2.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow2);
        layoutRow2.addClassName(Gap.MEDIUM);
        layoutRow2.setWidth("100%");
        layoutRow2.getStyle().set("flex-grow", "1");
        textField8.setLabel("Name");
        textField8.getStyle().set("flex-grow", "1");
        textField9.setLabel("Affiliation");
        textField9.getStyle().set("flex-grow", "1");
        layoutRow3.setWidthFull();
        layoutColumn3.setFlexGrow(1.0, layoutRow3);
        layoutRow3.addClassName(Gap.MEDIUM);
        layoutRow3.setWidth("100%");
        layoutRow3.getStyle().set("flex-grow", "1");
        textField10.setLabel("Name");
        textField10.getStyle().set("flex-grow", "1");
        textField11.setLabel("Affiliation");
        textField11.getStyle().set("flex-grow", "1");
        layoutRow4.setWidthFull();
        layoutColumn2.setFlexGrow(1.0, layoutRow4);
        layoutRow4.addClassName(Gap.MEDIUM);
        layoutRow4.setWidth("100%");
        layoutRow4.getStyle().set("flex-grow", "1");
        textField12.setLabel("Username");
        textField12.getStyle().set("flex-grow", "1");
        textField13.setLabel("Password");
        textField13.getStyle().set("flex-grow", "1");
        textField14.setLabel("Confirm Password");
        textField14.getStyle().set("flex-grow", "1");
        loginForm.setWidth("100%");
        routerLink.setText("Already have an account? Sign in");
        routerLink.setRoute(CustomView.class);
        layoutColumn2.setAlignSelf(FlexComponent.Alignment.CENTER, routerLink);
        routerLink.setWidth("250px");
        layoutRow5.addClassName(Gap.MEDIUM);
        layoutRow5.setWidth("100%");
        layoutRow5.getStyle().set("flex-grow", "1");
        layoutRow5.setAlignItems(Alignment.CENTER);
        layoutRow5.setJustifyContentMode(JustifyContentMode.CENTER);
        buttonPrimary.setText("Sign Up");
        buttonPrimary.setWidth("min-content");
        buttonPrimary.addThemeVariants(ButtonVariant.LUMO_PRIMARY);
        buttonSecondary.setText("Cancel");
        buttonSecondary.setWidth("min-content");
        getContent().add(layoutColumn2);
        layoutColumn2.add(h3);
        layoutColumn2.add(formLayout2Col);
        formLayout2Col.add(textField);
        formLayout2Col.add(textField2);
        formLayout2Col.add(datePicker);
        formLayout2Col.add(textField3);
        formLayout2Col.add(emailField);
        formLayout2Col.add(textField4);
        formLayout2Col.add(textField5);
        formLayout2Col.add(comboBox);
        layoutColumn2.add(textArea);
        layoutColumn2.add(layoutColumn3);
        layoutColumn3.add(textMedium);
        layoutColumn3.add(layoutRow);
        layoutRow.add(textField6);
        layoutRow.add(textField7);
        layoutColumn3.add(layoutRow2);
        layoutRow2.add(textField8);
        layoutRow2.add(textField9);
        layoutColumn3.add(layoutRow3);
        layoutRow3.add(textField10);
        layoutRow3.add(textField11);
        layoutColumn2.add(layoutRow4);
        layoutRow4.add(textField12);
        layoutRow4.add(textField13);
        layoutRow4.add(textField14);
        layoutColumn2.add(loginForm);
        layoutColumn2.add(routerLink);
        layoutColumn2.add(layoutRow5);
        layoutRow5.add(buttonPrimary);
        layoutRow5.add(buttonSecondary);
    }

    record SampleItem(String value, String label, Boolean disabled) {
    }

    private void setComboBoxSampleData(ComboBox comboBox) {
        List<SampleItem> sampleItems = new ArrayList<>();
        sampleItems.add(new SampleItem("first", "First", null));
        sampleItems.add(new SampleItem("second", "Second", null));
        sampleItems.add(new SampleItem("third", "Third", Boolean.TRUE));
        sampleItems.add(new SampleItem("fourth", "Fourth", null));
        comboBox.setItems(sampleItems);
        comboBox.setItemLabelGenerator(item -> ((SampleItem) item).label());
    }
}
